/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.KhuyenMaiHoaDonBUS;
import DTO.ChiTietKhuyenMaiHoaDon;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class KhuyenMaiTheoHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form KhuyenMaiTheoHoaDon
     */
    public KhuyenMaiTheoHoaDon() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KhuyenMaiTheoHoaDon = new javax.swing.JPanel();
        KhuyenMaiHoaDon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kmTable = new javax.swing.JTable();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        viewAllButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        CTKhuyenMaiHoaDon = new javax.swing.JPanel();
        maKMLabel = new javax.swing.JLabel();
        giaHDLabel = new javax.swing.JLabel();
        ngayBDLabel = new javax.swing.JLabel();
        ngayKTLabel = new javax.swing.JLabel();
        maKMTextField = new javax.swing.JTextField();
        giaHDTextField = new javax.swing.JTextField();
        phanTramGiamTextField = new javax.swing.JTextField();
        ngayBDTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ngayKTTextField = new javax.swing.JTextField();
        phanTramGiamLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        KhuyenMaiHoaDon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        kmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khuyến Mãi", "Giá Hóa Đơn ", "Phần Trăm Giảm", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Trạng Thái"
            }
        ));
        jScrollPane1.setViewportView(kmTable);

        searchLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchLabel.setText("Tìm kiếm ");

        searchButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchButton.setText("Tìm kiếm");
        searchButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        viewAllButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewAllButton.setText("Xem tất cả");
        viewAllButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addButton.setText("Thêm");
        addButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KhuyenMaiHoaDonLayout = new javax.swing.GroupLayout(KhuyenMaiHoaDon);
        KhuyenMaiHoaDon.setLayout(KhuyenMaiHoaDonLayout);
        KhuyenMaiHoaDonLayout.setHorizontalGroup(
            KhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhuyenMaiHoaDonLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
            .addGroup(KhuyenMaiHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        KhuyenMaiHoaDonLayout.setVerticalGroup(
            KhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KhuyenMaiHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(viewAllButton)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
        );

        CTKhuyenMaiHoaDon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        maKMLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        maKMLabel.setText("Mã Khuyến Mãi");

        giaHDLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        giaHDLabel.setText("Giá Hóa Đơn");

        ngayBDLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ngayBDLabel.setText("Ngày Bắt Đầu");

        ngayKTLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ngayKTLabel.setText("Ngày Kết Thúc");

        giaHDTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Chi Tiết Khuyến Mãi");

        phanTramGiamLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        phanTramGiamLabel.setText("Phần Trăm Giảm");

        javax.swing.GroupLayout CTKhuyenMaiHoaDonLayout = new javax.swing.GroupLayout(CTKhuyenMaiHoaDon);
        CTKhuyenMaiHoaDon.setLayout(CTKhuyenMaiHoaDonLayout);
        CTKhuyenMaiHoaDonLayout.setHorizontalGroup(
            CTKhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CTKhuyenMaiHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CTKhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CTKhuyenMaiHoaDonLayout.createSequentialGroup()
                        .addGroup(CTKhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maKMLabel)
                            .addComponent(giaHDLabel)
                            .addComponent(ngayBDLabel)
                            .addComponent(ngayKTLabel)
                            .addComponent(phanTramGiamLabel))
                        .addGap(30, 30, 30)
                        .addGroup(CTKhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maKMTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(giaHDTextField)
                            .addComponent(phanTramGiamTextField)
                            .addComponent(ngayBDTextField)
                            .addComponent(ngayKTTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CTKhuyenMaiHoaDonLayout.setVerticalGroup(
            CTKhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CTKhuyenMaiHoaDonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(CTKhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maKMLabel)
                    .addComponent(maKMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CTKhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giaHDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giaHDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CTKhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phanTramGiamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phanTramGiamLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CTKhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngayBDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayBDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CTKhuyenMaiHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngayKTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayKTLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout KhuyenMaiTheoHoaDonLayout = new javax.swing.GroupLayout(KhuyenMaiTheoHoaDon);
        KhuyenMaiTheoHoaDon.setLayout(KhuyenMaiTheoHoaDonLayout);
        KhuyenMaiTheoHoaDonLayout.setHorizontalGroup(
            KhuyenMaiTheoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhuyenMaiTheoHoaDonLayout.createSequentialGroup()
                .addComponent(KhuyenMaiHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CTKhuyenMaiHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        KhuyenMaiTheoHoaDonLayout.setVerticalGroup(
            KhuyenMaiTheoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhuyenMaiTheoHoaDonLayout.createSequentialGroup()
                .addGroup(KhuyenMaiTheoHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KhuyenMaiTheoHoaDonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CTKhuyenMaiHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(KhuyenMaiHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KhuyenMaiTheoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KhuyenMaiTheoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void viewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewAllButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addFrame.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) kmTable.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        listKMHD = kmhdBUS.getDanhSachKhuyenMaiHoaDon();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date today = new Date();

        for (ChiTietKhuyenMaiHoaDon km : listKMHD) {       
            model.addRow(new Object[]{
                km.getMaKM(),
                km.getGiaHoaDon(),
                km.getPhanTramGiam(),
                sdf.format(km.getNgayBatDau()),
                sdf.format(km.getNgayKetThuc()),
                km.getTrangThai()
            });
        }
    }

    private List<ChiTietKhuyenMaiHoaDon> listKMHD = new ArrayList<>();
    ThemKMTheoHD addFrame = new ThemKMTheoHD();
    KhuyenMaiHoaDonBUS kmhdBUS = new KhuyenMaiHoaDonBUS();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CTKhuyenMaiHoaDon;
    private javax.swing.JPanel KhuyenMaiHoaDon;
    private javax.swing.JPanel KhuyenMaiTheoHoaDon;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel giaHDLabel;
    private javax.swing.JTextField giaHDTextField;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kmTable;
    private javax.swing.JLabel maKMLabel;
    private javax.swing.JTextField maKMTextField;
    private javax.swing.JLabel ngayBDLabel;
    private javax.swing.JTextField ngayBDTextField;
    private javax.swing.JLabel ngayKTLabel;
    private javax.swing.JTextField ngayKTTextField;
    private javax.swing.JLabel phanTramGiamLabel;
    private javax.swing.JTextField phanTramGiamTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton viewAllButton;
    // End of variables declaration//GEN-END:variables
}
