/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author xuand
 */
import DAL.TaiKhoanDAL; // Lớp này cần được tạo để truy xuất bảng TaiKhoan
import DTO.TaiKhoan;   // Lớp TaiKhoan chứa các thuộc tính: maNV, matKhau, tenNV, chucVu, maTK, ...
import SESSION.CurrentSession;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
        private TaiKhoanDAL taiKhoanDAL;
    public Login() {
        initComponents();
        setUpEnterKey();  // Kích hoạt sự kiện Enter
        taiKhoanDAL = new TaiKhoanDAL();
 
    }
    private void setUpEnterKey() {
        txtMaNV.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    btnDangNhap.doClick(); // Giả lập sự kiện click vào btnDangNhap
                }
            }
        });

        pwdMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    btnDangNhap.doClick(); // Giả lập sự kiện click vào btnDangNhap
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        pwdMatKhau = new javax.swing.JPasswordField();
        btnDangNhap = new javax.swing.JButton();

        jLabel1.setText("Đăng nhập");

        jLabel2.setText("Mã Nhân Viên");

        jLabel3.setText("Mật Khẩu");

        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pwdMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtMaNV)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnDangNhap)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(pwdMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnDangNhap)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
         String maNVStr = txtMaNV.getText().trim();
        String matKhau = new String(pwdMatKhau.getPassword()).trim();
        
        if (maNVStr.isEmpty() || matKhau.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ mã nhân viên và mật khẩu!");
            return;
        }
        
        int maNV = 0;
        try {
            maNV = Integer.parseInt(maNVStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên phải là số!");
            return;
        }
        
        // Lấy đối tượng TaiKhoan từ CSDL theo maNV
        TaiKhoan tk = taiKhoanDAL.getTaiKhoanByMaNV(maNV);
        if (tk == null) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên không tồn tại!");
            return;
        }
        
        // So sánh mật khẩu (có thể cần mã hóa, tùy theo cách lưu trữ)
        if (!tk.getMatKhau().equals(matKhau)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không đúng!");
            return;
        }
        
        // Đăng nhập thành công, lưu thông tin vào CurrentSession
        CurrentSession.setMaNV(tk.getMaNV());
        //CurrentSession.setTenNV(tk.getTenNV());
        CurrentSession.setMaTK(tk.getMaTK());
        CurrentSession.setChucVu(tk.getChucVu());
        
        // Mở giao diện MainWindow (giả sử bạn có MainWindow là JFrame)
        new MainWindow().setVisible(true);
        // Đóng cửa sổ đăng nhập
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btnDangNhapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pwdMatKhau;
    private javax.swing.JTextField txtMaNV;
    // End of variables declaration//GEN-END:variables
}
